### ISSUE TITLE
No way to provide donation

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#11]
I would like to donate some money to help this project, but I don't see any way to do that.

**Comment by nvbn** [comment]
Fixed in README.rst or:
PayPal: nvbn.rm@gmail.com
Yandex Money: 410011244953574
=)

**Comment by hdave** [comment]
$50 sent....keep up the good work.

You may also want to put that information in an "About" dialog on the 
application indicator with a clickable link...

**Comment by nvbn** [comment]
Thank you =)
Now application doesn't have about dialog. When dialog created i will add link to github with this information.
