### ISSUE TITLE
Note window resize bug

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#113]
When a note window is stretched beyond a certain height the geometry calculation fails for the attachment area.  See screenshot:

https://dl.dropbox.com/u/3891104/Screenshot%20from%202012-10-23%2009%3A06%3A09.png

**Comment by fmoo** [comment]
@hdave - I _think_ this is fixed in master with 5b33f4e0ce6475c29c19123672728dda0a6c1b44.  Can you confirm?

**Comment by hdave** [comment]
From the code it looks like it is fixed, but I am unable to build from source and must wait for an update to the PPA to confirm.  I am a developer, but am unfamiliar with Python.  Are there instructions anywhere on how to build and run the system from source?  What IDE do you use for this?

**Comment by fmoo** [comment]
Assuming you don't already have git installed, but have the ppa added, something like this should work.

```
sudo apt-get install git
sudo apt-get build-dep everpad
git clone git://github.com/nvbn/everpad.git everpad-git
cd everpad-git
sudo python setup.py develop
```

Then make sure you've closed the indicator (click Exit from the everpad unity applet(?)) and back on the console:

```
python everpad/pad/indicator.py
```

When you're done, you should be able to run 

```
sudo python setup.py develop --uninstall
```

To restore your environment back to the ppa version

**Comment by fmoo** [comment]
I just tossed up a wiki node here:  https://github.com/nvbn/everpad/wiki/developing-for-everpad

@nvbn feel free to link to this from the main page and update as you feel necessary.

**Comment by hdave** [comment]
Great -- thanks.
