### ISSUE TITLE
Random semi-colons appearing in notes in latest update.

### ISSUE THREAD

**Issue by cas--** [nvbn/everpad#114]
With the latest update on Ubuntu I am now seeing semi-colons ";"  appearing throughout the text of notes and in some I am also seeing the text "sp;".

From what I can tell it is something to do with whitespace as it appears in every cell of a table, end of lines or between multiple spaces.

I checked in nixnote and they are not there until it is opened in everpad and then it saves them.

Just to update I created a new note with the following text:

```
New note content   test
abc     test     12345


more text    text
```

Save, closed and reopened:

```
New note contentp; test
abcp;p; testp;p; 12345
;;
;;
more textp;p;text
```

**Comment by jmoronat** [comment]
Same problem here.

**Comment by fmoo** [comment]
What was the flow you're doing to repro?  Are you creating the note with everpad opening/saving in nixnote and then re-opening with everpad?

**Comment by cas--** [comment]
The flow was all on everpad

**Comment by cas--** [comment]
Looks like its this commit: https://github.com/nvbn/everpad/commit/62e39a44ef9fceaa2da564d127073d2801121d02

**Comment by fmoo** [comment]
@cas-- @jmoronat - were you all running the ppa version or master?

**Comment by jmoronat** [comment]
I'm running the ppa version.

**Comment by fmoo** [comment]
@nvbn - can you roll a new ppa release with 2309edd9ea6f08f8b5ccb4cd47d02e47dec49c0f ?

**Comment by nvbn** [comment]
I will push update to ppa today.
