### ISSUE TITLE
Create Note and Last Sync options should be at top of indicator

### ISSUE THREAD

**Issue by cas--** [nvbn/everpad#116]
Currently it is quite unwieldy to traverse 20 notes to get to these buttons at the bottom and as they are often used I feel they should be moved to the top. Although I don't use the `Last Sync` option as much as `Create Note` it is in the same grouping of common used options.

```
Create Note
All Notes
Last Sync
```

Also to save a little vertical space the bar between `Setting` and `Exit` could be removed.

**Comment by vgarvardt** [comment]
I don;t think this is good idea. Agree about moving Create Note to the top but Sync should stay at the bottom, next to Settings as this operation is used rarely in common.

**Comment by cas--** [comment]
I agree clicking on it is a less common action however I need to ensure it it updated before I suspend the computer so that my mobile retrieves latest version (being at the top makes this action faster) and also since I moved Sync to the top it makes viewing the last time it updated clearer since my eyes are already at the top of the indicator. The only downside is that it pushes the notes one more level down but I feel that is a small price for the overall usage of having Sync at the top.

**Comment by nvbn** [comment]
"display" items should stay in top, actions in bottom. If it changed - it's a big interface issue. Synchronization time is not important, is the additional information. And most users created notes less than looks. If you want to quickly create a note use launcher or HUD.

**Comment by nvbn** [comment]
Maybe we need to create settings option for "actions on top"?

**Comment by hdave** [comment]
I agree with vgarvardt - its a reasonable compromise to put create note at the top and leave all others at the bottom.   

I would add that, in my opinion, I would drop "All Notes" to the bottom as well.  Why?  Because the Dash Lens is already an awesome note browser, though I do see the value in the All Notes window.

**Comment by vgarvardt** [comment]
For me All Notes is the most visited menu item in indicator menu.

**Comment by cas--** [comment]
Had a few thoughts about the fact that everyone has different ideas of menu placement so I ended up writing a settings tab page that allows you to move every item around: 

![Imgur](http://i.imgur.com/7BbbQ.png)

I've only just got the whole process working so it needs quite a bit of cleanup however I thought you guys might be interested and comments would be welcome. 

https://github.com/cas--/everpad/tree/Feature/EditableMenuPosition

**Comment by cas--** [comment]
Reworked the ui code and managed to fit it onto the Appearance tab. The order can be changed by using drag'n'drop or context menu and is saved automatically.

![Imgur](http://i.imgur.com/Ha0hbl.png)

**Comment by duizendnegen** [comment]
Why has this not been pulled into the main repository yet? Great feature imo.

**Comment by jrgifford** [comment]
Any status on this?

**Comment by duizendnegen** [comment]
@nvbn - what about pulling @cas-- commit? Or do you want me to merge it and create a pull request?

**Comment by cas--** [comment]
I have been busy with other projects but I can revisit the code for a pull request. In it's current state I do not think it will apply cleanly to the current git head plus there were a few changes I wished to make.

**Comment by jrgifford** [comment]
Ok, if you could do that, that'd be great. This change looks fairly useful. :)
