### ISSUE TITLE
Notes Not Syncing

### ISSUE THREAD

**Issue by bendangelo** [nvbn/everpad#118]
I just noticed all my notes have not synced to evernote. Its says last sync was 1 minute ago. I tried syncing again but nothing.

Anyone know whats happening?

**Comment by hdave** [comment]
kill everpad-provider and run it within a terminal via:

`everpad-provider --verbose`

if it complains about bad XML tags, delete ~/.everpad and relogin.   Ensure you are running the latest.

**Comment by bendangelo** [comment]
I got this output:

```
Tag nodejs local
EDAMUserException(errorCode=10, parameter='Tag.name')
```

I have a tag named nodejs.

**Comment by hdave** [comment]
What version are you running?

**Comment by bendangelo** [comment]
I'm not sure. I tried running:

```
everpad --version
everpad-provider --version
```

But got nothing.

**Comment by bendangelo** [comment]
Package: everpad
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 1647
Maintainer: Vladimir Yakovlev nvbn.rm@gmail.com
Architecture: amd64
Version: 2.0.1-0~precise
Depends: python-pyside.qtcore, python-pyside.qtgui, python-dbus, python-beautifulsoup, sni-qt, python-pysqlite2, python-keyring, python-support, python-sqlalchemy, python-oauth2, python-unity-singlet, python-magic, python-pyside.qtwebkit, python-html2text
Description: Ubuntu integrated evernote client
 Evernote client with unity integration
Homepage: https://github.com/nvbn/everpad/

Thats what I got.

**Comment by fmoo** [comment]
@bendangelo - how did you create the note?   With everpad? And what do you mean by:

> I have a tag named nodejs.

?

**Comment by bendangelo** [comment]
I created all the not syncing notes with everpad.

I was referring to the error message: Tag nodejs local

**Comment by bendangelo** [comment]
So I been playing around with it. Looks nothing is being synced at all. I ran everpad in the terminal and I get this issue when clicking on notebooks inside the Everpad / All Notes window.

```
QSpiAccessible::accessibleEvent not handled:  "8008"  obj:  QObject(0x0)  " invalid interface!" 
```

**Comment by fmoo** [comment]
@bendangelo - did you run the provider in --debug mode as well?  Anything in the log when clicking "sync" from the menu?

**Comment by bendangelo** [comment]
Said unrecognised arguments on both everpad and everpad-provider. It sometimes crashes when I close or restart. I'm sending all these reports.

**Comment by fmoo** [comment]
I meant --verbose I think.  Sorry.  On mobile.

**Comment by bendangelo** [comment]
Yeah tried that. Trying agian:

```
Tag nodejs local
EDAMUserException(errorCode=10, parameter='Tag.name')
```

Same issue as before. Also I just updated everpad to the latest version. Still nothing is syncing.

**Comment by hdave** [comment]
As a workaround -- blow away from ~/.everpad directory and resync.  My 
guess is your problem will be gone.  The question is...has whatever 
caused the problem been fixed?

I used to get errors like that all the time, but they are fewer lately...

**Comment by bendangelo** [comment]
Ok I just removed .everpad folder and it now syncs!

**Comment by hdave** [comment]
Then I'd close this issue and open another one if it happens again. Hopefully if it does, you can give the developers the steps to reproduce...though I found that easier said than done.
