### ISSUE TITLE
Check for everpad running and restart it when updating from PPA

### ISSUE THREAD

**Issue by vgarvardt** [nvbn/everpad#119]
Check if daemon, lens and indicator is running and restart them to use latest version. Currently it is possible exit and run indicator again, but lens and provider remains old - this causes indicator crash. The only way to restart them - manually kill from command line (or computer restart =)).

Another option - add something like Kill menu option to indicator that will not only exit indicator but also kill provider and lens.

**Comment by fmoo** [comment]
Yeah, this sort of bit me yesterday when trying to figure out why the html2text wasn't working in lens.

I was thinking for #115, some dbus methods could be added to facilitate version detection here (e.g., getVersion), and then a simple script could be used to query each service for its running version and then kill/restart each appropriately.

**Comment by hdave** [comment]
For me, this would be huge.  I have a complicated work set up on my PC and it is a real pain to log out and log back in to get the new lens.

**Comment by vgarvardt** [comment]
@hdave why don't you use workaround for this?

killall everpad everpad-provider everpad-lens

**Comment by hdave** [comment]
Thats what I do, but the lens never seemed to restart for me.  But trying it again right now, I see that the Dash automatically restarts evernote-lens and evernote-provider.   And so does starting Everpad (indicator).  This is cool -- didn't know that.

So really, all we have to do is add a simple script to do that after installation:

`killall everpad everpad-provider everpad-lens`

doesn't even need super user priviledges.

**Comment by hdave** [comment]
Actually there is a problem with this.  Killing evernote-provider leaves the lock file in the tmp directory and so subsequent attempts to run it fail.

**Comment by nvbn** [comment]
Added in latest release(2.1) and will normally work when everpad updated to the next release with api changes.
