### ISSUE TITLE
Wishlist: View all notes by Tags

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#122]
It would be nice if the "All Notes" dialog offer the option to view the notes by Tag instead of by Notebook.

**Comment by fmoo** [comment]
Do you happen to know of lens / scope search by tag works?

**Comment by hdave** [comment]
searching lens by tags works great actually...good point.   Come to think of it, we really don't need an "all notes" window at all with the Unity lens!

**Comment by vgarvardt** [comment]
It was me who implemented All Notes feature - I missed it a lot after Tomboy/Gnote usage. I don't like lens search and prefer notes sorted by categories but I'm sure it's great when there are several ways to do same things - some people like this way and some that way.

I was going to implement Tags in addition to Categories, I have an idea how to do this, but now I'm a bit busy. Will try to find some time to handle this if no one will implement this before I do.

**Comment by hakonaj** [comment]
As a humble user of Everpad I prefer the All Notes view over the lens search. I usually sort by last modified and work on my most recent updated notes, but it would be great with search functionality in the All Notes view as well.

**Comment by hdave** [comment]
Thats a good point about sort by last modified, you can't do that in the lens.

**Comment by fmoo** [comment]
To be fair, the lens search should be improved to return most relevant with most recent as a tie breaker.

I really like the all notes view as well and was thinking of taking a stab adult adding a tab view to show all by tag/category/etc

**Comment by duizendnegen** [comment]
I would like to work on this feature.

**Comment by vgarvardt** [comment]
fork'n'implement =)

**Comment by duizendnegen** [comment]
Yep, it's nearly done.
