### ISSUE TITLE
Pin note in indicator

### ISSUE THREAD

**Issue by vgarvardt** [nvbn/everpad#124]
Currently indicator menu displays 20 last modified notes. It would be nice to have Gnote-like pin note feature - pinned notes always stay at the top of the list.

**Comment by utkarshsins** [comment]
I was also thinking along similar lines. Instead of plain last 20 modified notes, it would be helpful if we can get 
- Pinning feature for some notes, 
- Organizational indicator, like colored bullets representing the Notebook in front of each note in the list.

**Comment by hdave** [comment]
+1 

Tomboy had this pinning capability and it was awesome.  Would always keep my top 10 programming reference notes pinned.  I think the idea was that if you had 8 notes pinned then you got to see 12 (e.g. 20 - 8) most recently modified notes.  Very helpful idea.

**Comment by fmoo** [comment]
If it's "sticky", they can be called "Sticky Notes" :)

**Comment by thameera** [comment]
+1
This would be a pretty useful feature to have. Like the smart bar (is that how it's called?) in the official Windows client. Everyone has these two or three notes they need to access all the time.
