### ISSUE TITLE
Additional editing keyboard shortcuts 

### ISSUE THREAD

**Issue by msbentley** [nvbn/everpad#128]
For dedicated note writing and editing, a few more keyboard shortcuts would be super useful. I've included some examples, based on Evernote and other apps. The list of EN shortcuts is at https://support.evernote.com/link/portal/16051/16058/Article/625/What-are-the-keyboard-shortcuts-in-Evernote-for-Windows

The important ones for me:

Ctrl-Shift-V - paste as plain text 
Ctrl-Shift-B - start/stop bulleted list
Ctrl-Shift-O - start/stop ordered (numbered) list
Ctrl-K - insert hyperlink
Ctrl-S - save note

A shortcut to jump to the tag box would also be useful - EN uses Ctrl-Alt-T, but this clashes with the default gnome terminal shortcut...

Cheers, Mark

**Comment by nvbn** [comment]
Hm, we need to implement most of this hotkeys =)

**Comment by nvbn** [comment]
#162 is more detailed
