### ISSUE TITLE
Could you please write more about develop documents?

### ISSUE THREAD

**Issue by keepzero** [nvbn/everpad#129]
I want have a try to code for everpad, but I don't know how to start. 

Such as what library everpad required, which Python package everpad used.
And I use Archlinux, how to disable the feature only available on Ubuntu?

**Comment by nvbn** [comment]
For start developing read https://github.com/nvbn/everpad/wiki/developing-for-everpad

**Comment by nvbn** [comment]
For disabling ubuntu specific features not run lens =)

**Comment by e2jk** [comment]
@keepzero Is your question answered? If so, please close this issue so that the developers can more easily identify open issues.
