### ISSUE TITLE
Ctrl-C copy shortcut forces unaltered notes to save

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#130]
If I open a note, select some text, and hit Ctrl-C to copy the text out, the note is flagged as having been modified and is "saved" locally when closed.  I would excepted that Everpad recognize the note was unaltered.

I believe it is using the Ctrl-C key that causes the issue.  If I open a note, select text, click right and copy the text from the context menu, then the note is not saved when closed.

**Comment by nvbn** [comment]
It's present in 2.2?

**Comment by hdave** [comment]
Fixed in 2.2.0
