### ISSUE TITLE
Show Last Sync as a delta time

### ISSUE THREAD

**Issue by cas--** [nvbn/everpad#137]
I don't find it very useful having the last sync as a time because I then have to check the actual time and work out the difference. I propose a last sync delta that shows time in minutes:

![Screenshot](http://i.imgur.com/a0P8r.png)

Code Examples:
[Based upon time returned by get_last_sync](https://github.com/cas--/everpad/compare/upstream-master...Feature;Convert_last_sync_to_delta)
[Create get_last_sync_delta func](https://github.com/cas--/everpad/compare/upstream-master...Feature;Last_Sync_Delta)

**Comment by hdave** [comment]
+1 for this.

**Comment by nvbn** [comment]
Create pull request and i will merge it
