### ISSUE TITLE
"Open with... Everpad" doesn't import file

### ISSUE THREAD

**Issue by msbentley** [nvbn/everpad#145]
In Nautilus there is an "Open With" entry for Everpad. I assumed this would create a new note and insert the file. I tested this with an image - a new note opens, but no content is inserted.

**Comment by nvbn** [comment]
What os and version you use?

**Comment by msbentley** [comment]
Ahh, my bad - I assumed that the imported image would be displayed "in-line", whereas it just shows as "1 attached files". So it is working as expected! Thanks, Mark
