### ISSUE TITLE
New note created in Everpad and saved not in Evernote

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#15]
I can reproduce this regularly:

1) Using the application indicator "Create Note"
2) Edit the note
3) Save the note
4) See the "Note saved" notification appear
5) Go to Evernote...newly created note cannot be found
6) Newly created note is not in list of notes on the application indicator

**Comment by hdave** [comment]
After I quit Everpad and restarted my machine...it appeared.

Also, if I re-authorize, it appears.

Perhaps there is a delay until the next sync?

**Comment by nvbn** [comment]
Notes sync every 5 minute
