### ISSUE TITLE
Unable to Perform First Sync

### ISSUE THREAD

**Issue by hamlindsza** [nvbn/everpad#151]
Hi All,

I just installed everpad 2.0.1 Ive authorized Everpad to use my Evernote account. Clicked on Please perform first sync. But nothing happens :(

Ive done:
killall everpad everpad-provider everpad-lens

everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 66, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 82, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 57, in get_note_store
    http_proxy=get_proxy_config(urlparse(user_store_uri).scheme))
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 72, in **init**
    raise ValueError("Unsupported Proxy Scheme, %s" % http_proxy.scheme)
ValueError: Unsupported Proxy Scheme, https

I had applied a system wide proxy settings. I have even tried removing the proxy settings put get the same error as above.

Im extremely sorry if this is not the right place to post in my problem, if so please let me know where should i post in my query.

**Comment by fmoo** [comment]
When you modify your proxy settings, you need to start a new terminal session in order for the changes to be picked up.

Just out of curiosity, are you really using an HTTP proxy that you can connect to over SSL? Or are you trying to talk SSL over an HTTP proxy?

**Comment by hamlindsza** [comment]
Tried after a restart it worked :) Thanks :)

I was using squid. I guess it supports both HTTP & HTTPS

**Comment by fmoo** [comment]
> I was using squid. I guess it supports both HTTP & HTTPS

It shouldn't be incorrect to specify `env: {"https_proxy": "http://my_squid_proxy:8080"}`, since this is making an HTTP connection to your squid proxy for making outbound https CONNECTions, but if you legitimately want to connect via https _to_ a proxy server, this seems like a use case we should support.

I've never seen this particular proxy configuration in production, but that doesn't make it incorrect or invalid.  If you need to connect to the https service via a proxy that you must connect to over https:// then you should consider reopening this.

**Comment by choyj** [comment]
I'm seeing the exact same problem.  My /etc/apt/apt.conf looks like this:
Acquire::http::proxy "http://web-proxy.xxxx.com:8080/";
Acquire::https::proxy "https://web-proxy.xxxx.com:8080/";
Acquire::ftp::proxy "ftp://web-proxy.xxxx.com:8080/";
Acquire::socks::proxy "socks://web-proxy.xxxx.com:8080/";

I also tried killing everpad-provider, opening a terminal, unset the https_proxy parameter and tried running it manually.  That got rid of the error, but when I select "Please perform first sync", nothing happens.

Odd that it's complaining about https being an unsupported proxy scheme.  How can I reopen this bug?
