### ISSUE TITLE
Question: Localization strategy

### ISSUE THREAD

**Issue by mhaggag** [nvbn/everpad#158]
Hello.

I usually have everpad installed from source (from my fork) and keep it up to date in terms of localization, on a daily basis (whenever new features/strings are added, I translate them). Is it OK for me to issue pull requests whenever I do localization updates, or would you prefer localization pulls to be done prior to releases only? (or weekly, monthly, etc.)

I ask because I don't want to waste your time continuously reviewing and merging non-critical pulls if your time is limited :)

Thanks.
--Muhammad

**Comment by nvbn** [comment]
Create branch only with changes in translation files, create pull request. And i'll merge it. It's a simplest way.
