### ISSUE TITLE
Everpad cannot sync

### ISSUE THREAD

**Issue by niuhuifei** [nvbn/everpad#159]
In Ubuntu 12.10, after syncing some times, now it does not sync anymore. Everytime it need to re authorise  again and can work for some days, and then the same problems occur again. All local contents in computer without syncing will lost if re-authorizing.  Please please please fixing this!

**Comment by nvbn** [comment]
Please run 

<pre>
killall everpad-provider
everpad-provider --verbose
</pre>

and try to sync

**Comment by berart** [comment]
Hello! I think I have the same issue. Everpad will not sync. New or edited external notes are not downloaded and local notes are not uploaded. Did what you suggested and got the following:

Tag Deploy local
EDAMUserException(errorCode=10, parameter='Tag.name')

Thanks for looking into this!

**Comment by nvbn** [comment]
Try to remove ~/.everpad/ and run sync

**Comment by berart** [comment]
Thanks. It appears to be working now.

**Comment by fmoo** [comment]
Is it worth trying to make everpad detect this and clean it up automatically?  It seems there have been a fair number of reports along these lines.

**Comment by hdave** [comment]
Should this issue be closed?
