### ISSUE TITLE
Bug: attachments added to a note using Everpad do not show up in Evernote web

### ISSUE THREAD

**Issue by giacecco** [nvbn/everpad#164]
When you attach a file like a PDF to a note in Everpad and then try to access the same on Evernote web after synchronisation, the web attempts displaying the PDF  (you see the "Loading note data..." message in the note pane for 1 second) but then nothing is displayed.

Applies to the current Everpad version at the moment of writing: 2.2.1-0.

Thanks!

P.S. If you are reading this and are interested in this feature, too, I have donated using Flattr. [Did you?](http://giacec.co/SgxwOn)

G.

**Comment by maksymov** [comment]
confirmed

**Comment by GertjanvanhetHof** [comment]
When is this bug solved? This bug is still not working in 2016 and reported in 2012.
