### ISSUE TITLE
"Start with System" setting fails if you don't already have an autostart directory

### ISSUE THREAD

**Issue by MattFlower** [nvbn/everpad#165]
I installed everpad on a brand new installation of Ubuntu 12.  I had a .config directory, but didn't yet have an autostart directory.  This caused the "Start with System" setting to fail.

**Comment by joelkrueger** [comment]
I can confirm this bug on Ubuntu 12.04.1 with Everpad 2.2.1-0~precise

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 141, in auto_start_state
    self.startup_file,
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/home/itsme/.config/autostart/everpad.desktop'

To reproduce: Without a /home/{user}/.config folder in existence, start Everpad, click on the tray icon, select Settings and Management, click on "Start with system" and the error is generated.
