### ISSUE TITLE
Title misses "<something>"

### ISSUE THREAD

**Issue by zhoulike** [nvbn/everpad#166]
The title of some notes is like this: <Funny book>-Chapter 1
In the notes list, the title is "<Funny book>-Chapter 1". When I open this note, the title becomes "-Chapter 1". If I modify the content of the note and save it, the title displayed in the notes list becomes "-Chapter 1". However, title like "《Funny book》-Chapter 1” or "Funny book-Chapter 1” is OK!

**Comment by fmoo** [comment]
Sounds like an html double-unescaping issue...  :/
