### ISSUE TITLE
Everpad clobbers notes changed in other clients

### ISSUE THREAD

**Issue by freelock** [nvbn/everpad#171]
Hi,

Everpad has a great client experience, but I hit a very serious bug: it can clobber notes that have been changed elsewhere.

I am currently running Everpad on two computers, one at work and one at home. Apparently when I left the office, and had shut down the computer for the night, it hadn't sync'd its notes, because some were not there when I got home. 

At home I edited some existing notes and made sure to sync. When I got to the office, my edited notes were available on my phone. After starting up the office computer and sync'ing, the notes reverted to the state they were on the office instance, clobbering the work I had done at home!

I also use NixNote, and I'm liking Everpad much better overall. But this issue is a killer! I have noticed that Nixnote does occasionally copy a note and add "conflicted version" to the title -- at a minimum doing something like this before sync'ing a note would be a huge improvement.

**Comment by hdave** [comment]
Issue #134 solves half of this problem because after editing a note in Everpad it will be immediately sync'd to the server (not a full sync...just that one note).

What else is needed is that when a user opens a note in Everpad a quick check should be performed in order to determine if that note had been modified on the server since the last Everpad sync.

Together, I believe these capabilities will solve this problem.

**Comment by cas--** [comment]
There is an issue with the signature for create note with these latest commits:

```
ERROR:dbus.connection:Unable to set arguments ((0, u'New note', u'New note content', 0, 0, 0, dbus.Array([], signature=dbus.Signature('i')), '', None, None, None),) according to signature u'(issxxiassbiai)': <type 'exceptions.TypeError'>: an integer is required
Traceback (most recent call last):
  File "/home/calum/projects/everpad/everpad/pad/indicator.py", line 154, in create
    self.app.provider.create_note(note_struct),
  File "/home/calum/projects/everpad/everpad/tools.py", line 28, in wrapper
    return fnc(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: an integer is required
```

**Comment by nvbn** [comment]
@cas-- It's working now?

**Comment by cas--** [comment]
Nope it is still not working. The create note argument are set to `None` for `conflict_parent` and `conflict_items` which is why it's failing. So it seems to defaults for these arguments are not being setup correctly.
