### ISSUE TITLE
Ubuntu 12.04 GNOME Shell No Everpad Icon

### ISSUE THREAD

**Issue by fleamour** [nvbn/everpad#173]
Everpad is set to run on start up & I can access  it via everpad --settings  but there is no icon in system tray so cannot access notes.

**Comment by nvbn** [comment]
Gnome shell tray not properly work with qt apps, install https://extensions.gnome.org/extension/495/topicons/ for fixing it

**Comment by fleamour** [comment]
Unfortunately that particular extension will not stick.  : (

**Comment by fmoo** [comment]
Is there some other interface that needs to be implemented in order to integrate with gnome's system tray?  Or is this something Qt/PySide needs to fix?

**Comment by fleamour** [comment]
Apparently extension will only work with GNOME 3.6 it does not work with 3.4 LTS version.  I'm guessing it will not be back ported.  Some times Linux innovates too fast!  Not leaving the comforts of LTS is one of my general rules.

**Comment by Orbmiser** [comment]
Kernal 3.5.0-17 generic 64bit 
Yep had the same issue Cinnamon 1.6 solved by editing autostart applications.
bash -c "sleep 30; everpad %u"
As it was just I guess conflicting with trying to start with other at same time.

Don't know if that is the issue as still learning. So ignore if not your situation.

**Comment by Chratho** [comment]
Not sure whether this is related, but I have a similar problem with Ubunu 12.10 64bit/Gnome Shell. Everpad is configured for autostart, and the processes are acutally running, but more often than not, there appears no Everpad icon in the tray. So I need to manually `pkill everpad` and restart Everpad again. 

The gnome shell extension mentioned above is installed, Everpad version is 2.3 from PPA, Gnome Shell 3.6.2.

**Comment by Chratho** [comment]
Same issues for Everpad 2.4.

If I can provide you with any further information, let me know.

**Comment by Chratho** [comment]
Same issues for Everpad 2.5.

Still no one assigned? This is a quite annoying bug.

**Comment by igrossiter** [comment]
I have the same problem, sometimes the tray icon randomly appears and works, but it is very rare.

**Comment by rajlego** [comment]
Guys, I thought I had this same issue with gnome but I found that when I opened the bottom panel thing (by moving my cursor literally to the bottom of the screen) the icon would show up there.
