### ISSUE TITLE
Individual note window floats behind all notes window

### ISSUE THREAD

**Issue by KathyApplebaum** [nvbn/everpad#185]
First off, thanks for this program!

Just installed onto Mint 13 (Ubuntu offshoot). Synced fine, opened the window to show all notes, selected a note and double clicked. Note opened in a new window. All looks good.

Selected the newly opened window to bring it to the front, and it will not under any circumstances go in front of the all notes window. Makes it tough to see a note with large pictures unless I close the All Notes window.

**Comment by nvbn** [comment]
What DE you use?

**Comment by KathyApplebaum** [comment]
I'm sorry, I'm not familiar with the term DE.

**Comment by hdave** [comment]
Desktop Environment - e.g.  Unity, Gnome3, KDE, XFce...

**Comment by KathyApplebaum** [comment]
Oh, ta, hdave. I'm using Cinnamon, a fork of GNOME. (http://cinnamon.linuxmint.com/)
