### ISSUE TITLE
Sync error with unicode character

### ISSUE THREAD

**Issue by narnaud** [nvbn/everpad#186]
I'm using Evernote Food, and have some Notes with place names.
One of them is "rasserie André", and Everpad fails to load it (and stop the sync, meaning I can't see any other notes).

Here is the result of everpad-provider --verbose:
(ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. u'SELECT places.id AS places_id, places.name AS places_name \nFROM places \nWHERE places.name = ?' ('brasserie andr\xc3\xa9',)

**Comment by narnaud** [comment]
For the record, if I remove the accent it just works (obviously I would prefer to keep it)

**Comment by nvbn** [comment]
Hm, what version of sqlalchemy you use?

**Comment by narnaud** [comment]
I'm using everpad (ppa) on Ubuntu 12.10 up-to-date.

sudo apt-cache show python-sqlalchemy returns:
Version: 0.7.8-1

**Comment by lalov** [comment]
Hi, I'm also having problem using Everpad with unicode characters. 
If I create a note in Everpad containing for instance a "ø" (Norwegian character"), it is shown as "Ă¸ " in Evernote Web.
Creating / editing notes in Evernote web, containing "ø" is synced correctly to Everpad, but after editing it in Everpad and saving it it will look like "Ă¸ " in Evernote Web.
So it seems like the character is changed when uploading changes to the server, not when downloading them.
Please consider opening this bug again, or create a new if it is not related.

**Comment by Cutuchiqueno** [comment]
Same Problem here (Ubuntu 12.10, Everpad from ppa). Saving and/or syncing leads to wrong unicode characters
