### ISSUE TITLE
Please make Everpad search on the home lens optional

### ISSUE THREAD

**Issue by bodhin** [nvbn/everpad#191]
Having the Everpad lens on the Dash home lens slows down my poor old computer every time I open Dash. I wish it could be made optional to have it on the home lens.

For those who suffer of this some problem: I have removed the Everpad search from the home lens by opening /usr/share/pyshared/everpad/lens.py and searching for the following two lines:

search_in_global = True
self._lens.props.search_in_global = True

Change 'True' to 'False' on both lines. This change is not permanent - it will probably revert when Everpad is updated.

**Comment by krnekhelesh** [comment]
Please provide this option perhaps in the settings and management interface from the indicator.
