### ISSUE TITLE
Cursor is disappeared when typing in Korean

### ISSUE THREAD

**Issue by realgsong** [nvbn/everpad#200]
Version : 
Everpad version: 2.3
API version: 1
Schema version: 1

Symptom : 
Cursor is disappeared when typing in Korean.

Repro steps : 
1. Install Korean in Language Support
2. Add Korean input method in Keyboard Input methods
3. Create Note in everpad
4. Select Korean in your input method selection
5. type any things.

Expected : Cursor should not be disappeared
Actual : Cursor is disappeared after typing few keys. Workaround is pressting Alt+tab twice.

**Comment by realgsong** [comment]
It seems that this is a Pyside's issue. I confirmed it's reproduced with simple Pyside program which uses QWebView.

**Comment by realgsong** [comment]
FYI. Here's link to bug report https://bugreports.qt-project.org/browse/PYSIDE-137

**Comment by YaleHuang** [comment]
The same for Chinese.
