### ISSUE TITLE
Can't insert an image if I click on icon called  "insert image".

### ISSUE THREAD

**Issue by ghost66** [nvbn/everpad#204]
Can't insert an image if I click on icon called  "insert image".

I fix this error changing this line in editor.py file , I  put "self " in _insert_image.
I installed this app through his ppa yesterday.

def _insert_image(self):
        name = QFileDialog.getOpenFileName(
            filter=self.tr("Image Files (*.png *.jpg *.bmp *.gif)"),
        )[0]
        if name:
           self._insert_image_from_path(name)

**Comment by nvbn** [comment]
It is repeated in 2.4?

**Comment by ghost66** [comment]
nvbn,

Before this modification, I just had python 2.7.3 installed. Now I have python 2.7.3 e 3.2.3 installed.

**Comment by nvbn** [comment]
I meant everpad 2.4

**Comment by ghost66** [comment]
geraldo@Ghost66:~$ everpad --version
Everpad version: 2.3
API version: 1
Schema version: 1

**Comment by nvbn** [comment]
Try to update to latest release and check.

**Comment by ghost66** [comment]
Perfect ! I would like to suggest some improvements .
First -> You could put an information about version in the icon, like "About Everpad"
Second -> A feature for resizing the images.
Third - > A simple help in the context

Thank you for this excelent application, great job !
