### ISSUE TITLE
sync problems

### ISSUE THREAD

**Issue by white-hat** [nvbn/everpad#22]
With latest version of Everpad from ppa, not all notes are synced. Previous versions didn't work at all.
I have 14 notebooks, and Everpad synced 1 or 2 notes from each and says that sync is complete....

**Comment by hdave** [comment]
Total guess here -- Everpad syncs only the 20 most recently modified notes.

**Comment by white-hat** [comment]
Is there some reason for syncing only 20 notes?

**Comment by nvbn** [comment]
20 only in indicator, in lens you can see all notes.
Maybe application need option for change notes count in indicator.

**Comment by docaltmed** [comment]
I synced exactly 1 note from 1 notebook out of 300 notes. Unity Lens works ok for that one note,

**Comment by white-hat** [comment]
## Why not sync all notes? When I search notes via lens - nothing is found, because most of notes remain unsynced

Синхроним все заметки, но в lens отображаем только последние 20. Зато при поиске через lens - находятся все заметки, а не только 20, которым повезло засинхронизироваться.... Эхъ мне б чуть больше усидчивости - помог бы делом, а не советами :)

**Comment by hdave** [comment]
I can also confirm that only about 25 (or so) notes are visible via the lens, but I have over 400 notes in my account.  I don't see any rhyme or reason behind which ones got sync'd and which ones didn't.   Many of my notes have attachments.

I think showing only the 20 most last modified notes in the indicator is 100% the correct thing to do.

**Comment by nvbn** [comment]
Try to remove ~/.everpad/ and sync notes.
It's helped?

**Comment by hdave** [comment]
OK - I did rm -rf ~/.everpad and then re-synced via indicator (1.4.0 on Ubuntu 12.04 x64).  I think there are more than 20 notes, but not even close to all 400.  In the "Manage Notebooks" GUI from the indicator is it showing a total of about 20 notes across 8 notebooks.

I think that if a notebook has no notes that make your 20 most recently modified list, then no notes from those notebooks get synced.

**Comment by nvbn** [comment]
I fix some error with note with non real place and strange attributes in 1.5, maybe it is?

**Comment by docaltmed** [comment]
tried removing ./everpad/ and synced. Now I have no notes on the local machine.

**Comment by hdave** [comment]
version 1.5.0 gives the following:

```
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==1.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 7, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 19, in <module>
    import magic
ImportError: No module named magic
```

Taking a guess that it was a missing package:

`sudo apt-get install python-magic`

got me past this error, but still only 20-30 notes were synced.

**Comment by nvbn** [comment]
Fixed in 1.5.1, need update and restart everpad-provider, everpad-lens and everpad (or reboot).

**Comment by white-hat** [comment]
Oh, all synced! And now I can download and upload attachments. Great, thank You a lot!!!

**Comment by nvbn** [comment]
good =)

**Comment by acutbal** [comment]
Hello!!

I've installed Everpad v.1.8.2 in Ubuntu 12.04 64 bits and I'm experiencing syncing issues. I have about 700 notes organized in various notebooks, but only 96 notes are synced. I've already deleted .everpad folder. Also, I must reboot the laptop to be able to see my notes in the dash.

Best regards!!

PD: Apologize for my English, I'm from Spain...

**Comment by hdave** [comment]
It is my understanding that all Unity lenses will only show a maximum of 
100 items...but all 700 of your notes may be there...search for them in 
the lens, my guess is you will find them.

By the way -- I had the same thought you did at first.

**Comment by acutbal** [comment]
Hi!!

You're right!! My notes are all there, only a search is needed... I understand everything now!! Apologize for getting nervous so quickly.... Thus, congrats for this great app, that is what I've searching for a long time. It's very clever to use a lense for the notes!!

Best regards!!

PD: BTW, is it normal that the 3 processes together (everpad, everpad-lens and everpad-provider) use  200 mb of RAM? I use a HP G62 laptop with AMD cpu and gpu with Ubuntu 12.04 64 bits.

**Comment by acutbal** [comment]
Should I open a new issue then?

Enviado desde mi iPhone
