### ISSUE TITLE
Feature request: opening Everpad opens All Notes

### ISSUE THREAD

**Issue by duizendnegen** [nvbn/everpad#224]
Similar to how Clementine opens, first click of Everpad launches the doc icon, second click opens the All Notes window.
This should increase the use of Everpad in the Launcher significantly.
Again, I will most likely implement this soon.

**Comment by nvbn** [comment]
Yes, it's good idea.

**Comment by duizendnegen** [comment]
This has been implemented and will be included in a Pull Request soon.
