### ISSUE TITLE
Tags stack

### ISSUE THREAD

**Issue by duizendnegen** [nvbn/everpad#230]
Similar to #96 - different implementation though, because tags can nest indefintely.

**Comment by crypdick** [comment]
Hey @duizendnegen, could you point me to the relevant part of the code to see if I can take a whack at it? Maybe give me some tips as to how it should be done?

**Comment by duizendnegen** [comment]
https://github.com/duizendnegen/everpad/commit/893263acd8e2d90a27b8ebf4993e980635602c3e (in my private repo), the tag nesting is located elsewhere but should be similar
