### ISSUE TITLE
Bug: everpad overwrites changes made with other device/client

### ISSUE THREAD

**Issue by bullpup** [nvbn/everpad#232]
When I have a note open, and I change the note on another device/client and synchronize the other device/client, everpad does not notice that. Instead, everpad will overwrite the changes made on the other device/client, so all changes made on the other device/client are lost.

**Comment by nvbn** [comment]
What version of everpad you use?
In 2.4 in this situation note marks as "conflict"

**Comment by bullpup** [comment]
Ah, I am using 2.3 (ships with my distro). I guess I have to upgrade then...
