### ISSUE TITLE
Everpad on Ubuntu won't start with error that editor.html could not be found after update from nvbn-rm ppa

### ISSUE THREAD

**Issue by dolfandringa** [nvbn/everpad#262]
I just received an update of everpad on Ubuntu to 2.5.2-0~precise from the nvbn-rm ppa repository. After the update, everpad won't start with the following error (full traceback below):

IOError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/share/everpad/editor.html'

Ater complete purge and reinstall, the error changed to 
IOError: [Errno 2] No such file or directory: 'usr/share/everpad/editor.html'

If I look at where the file is located it is in: /usr/share/everpad/editor.html

So something is going wrong with absolute/relative paths in everpad, both after upgrade, and with a fresh install.

Could it be that in tools.py on line 154 'usr' should be '/usr'?

Cheers,

Dolf.

This is the full traceback after reinstallation:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 9, in <module>
    from everpad.pad.editor.content import ContentEdit
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 143, in <module>
    class ContentEdit(QObject):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 150, in ContentEdit
    _html = open(_editor_path).read()
IOError: [Errno 2] No such file or directory: 'usr/share/everpad/editor.html'

**Comment by johannestoger** [comment]
Hi! I found a fix - I'm running everpad on Ubuntu 12.04 LTS as we speak

I'm running version 2.5.2-0~precise from the PPA.

In /usr/lib/pymodules/python2.7/everpad/tools.py, the function resource_filename() - change 

```
return os.path.join('usr', file_name)
```

to

```
return os.path.join('/usr', file_name)
```

Note the slash in /usr.

**Comment by johannestoger** [comment]
Interestingly, there are two return statements in resource_filename...

**Comment by johannestoger** [comment]
#261 ?

**Comment by nvbn** [comment]
It fixed =)
pkg_resources.resource_filename not work with deb packages, two return statements is temporary fix.

**Comment by dolfandringa** [comment]
Thanks! The new update indeed works again. This is really fast fixing :+1:

**Comment by dolfandringa** [comment]
Ow, and wait! This new version is great. It also has a tags overview. :+1: :+1:
