### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Vistaus** [nvbn/everpad#267]
Hello,

thanks for this awesome program! Especially my dad enjoys using it and it keeps improving with every version. Those stacks are a welcome addition! :-)

But I noticed there was no Dutch translation yet and since I'm a translator for various programs I decided to take the plunge. So in the URL's below I put the Dutch translation. I'll keep updating the translation when new strings arrive :-)

https://sites.google.com/site/ubukuntu/downloads/nl.ts
https://sites.google.com/site/ubukuntu/downloads/nl.qm

**Comment by duizendnegen** [comment]
I will probably pull this into the official version soon. Hello, fellow Dutchy!

**Comment by Vistaus** [comment]
Thanks! And haha, great to see another Dutch guy on here! :D

**Comment by nvbn** [comment]
Release with translations pushed to ppa, thank you.

**Comment by duizendnegen** [comment]
Line 404 contains
"<translation>Laatste sync: %S minuut geleden</translation>"
while it should be
"<translation>Laatste sync: %s minuut geleden</translation>"
which causes the dropdown not to open.
I might fix this myself (once I figure out how to compile TS files) - or you can work on it, maybe?
