### ISSUE TITLE
can't access business notebooks

### ISSUE THREAD

**Issue by sdl75** [nvbn/everpad#299]
I have access to several business notebooks in the ordinary windows evernote client. But the do not show up in Everpad. Is this by design or is it a feature not yet implemented in Everpad? I have attached a dump of what I mean by business notebooks to clarify
![Screenshot from 2013-03-28 14:10:09](https://f.cloud.github.com/assets/2582421/313329/7cc8f7c0-97a9-11e2-8676-1ccfe5a5d6e7.png)

**Comment by sharpchi** [comment]
I'd definitely like to see this too.

**Comment by e2jk** [comment]
I assume those are shared notebooks, not notebooks of your own? Could be similar to #206.

**Comment by sharpchi** [comment]
Yes, in evernote's terminology Business notebooks that can be created with the business account, but which can be shared.  They're simply invisible in everpad, so I have to either use a windows client (i.e. log into Windows) or evernote's web client.

**Comment by zanyuk** [comment]
I do need access to shared notebooks in Everpad too. Probably, create a Pro version of Everpad with this feature enabled?

**Comment by e2jk** [comment]
Everpad is Free/Libre Open Source Software. We don't do in "Pro" versions ;)

Looking at the [Sharing Notes](http://dev.evernote.com/doc/articles/sharing.php) section of the Evernote documentation, the section "Synchronizing linked notebooks" has a link to a [synchronizing guide PDF](http://dev.evernote.com/media/pdf/edam-sync.pdf). Section "6. Linked Notebooks and Synchronization" of that PDF contains the information on how to do this (and also the explanation that "If a client also wants to access the contents of one or more shared
notebooks from other Evernote accounts, the process becomes a bit more complicated.")

Looks like that next to the regular Notebook objects, you'll need to handle LinkedNotebook objects which will link either to a Publishing (via the LinkedNotebook's uri property) or SharedNotebook (via the shareKey property) object. Any of these objects will then link to the actual Notebook object that is shared by the other user.

Extracts from the PDF:

```
Synchronizing information about other people’s notebooks that are linked into your
account requires two high-level additions to the basic synchronization scheme.
First, the client must keep an up-to-date list of all of the LinkedNotebook objects that
exist in the user’s account. [...]
Second, the client must use the information in user’s LinkedNotebooks to access the
corresponding shared Notebooks from the accounts and shards of the people who own those
notebooks. [...]
I.e. you must synchronize the list of LinkedNotebooks in your account to find the pointers
to other people’s notebooks. Then you use those pointers to synchronize the content of
the shared notebooks within other people’s accounts.
The synchronization process for a LinkedNotebook is similar to the process for
synchronizing to your own account, with a few changes.
```

It adds two levels of complexity extra. I'm not yet familiar with Everpad development. No promises, but I'll try to give it a look.

**Comment by e2jk** [comment]
Actually, since this is clearly a duplicate of #206, could you @sdl75 please close this issue and we'll concentrate on that other one? I'm duplicating my previous post there.
Reducing the number of open issues makes it easier for the developers to concentrate on the open issues. Thanks.

**Comment by sdl75** [comment]
Closed by request of ej2k
