### ISSUE TITLE
Everpad does not show note contents

### ISSUE THREAD

**Issue by tante** [nvbn/everpad#301]
With recent git checkouts Everpad no longer properly displays notes. The headers are fine in the context menu and the "All Notes" Notebook, but when opening a note, the window title just says
"Everpad / %(title)s"

and the note itself contains:

"%(title)s

%(content)s"

**Comment by duizendnegen** [comment]
I am not experiencing this issue.

Can you run, in a terminal
`killall everpad everpad-provider`
and then in two seperate terminals
`everpad-provider --verbose`
and
`everpad`
then try to sync and report on output shown in the terminal?

**Comment by tante** [comment]
Hmmm, seems to have been a bug with the version I had checked out, seems to work now.
