### ISSUE TITLE
openSUSE Request

### ISSUE THREAD

**Issue by fleamour** [nvbn/everpad#307]
Any plans on rpm build?

**Comment by Heart1010** [comment]
I support that request... really interested in an rpm build also.

**Comment by fleamour** [comment]
I want to use Ubuntu package Alien from CLI to convert deb to rpm, but how do I download latest deb?

**Comment by ghost** [comment]
There are debs here:
https://launchpad.net/~nvbn-rm/+archive/ppa/+files/everpad_2.5.6-0~precise_amd64.deb
https://launchpad.net/~nvbn-rm/+archive/ppa/+files/everpad_2.5.6-0~precise_i386.deb

These are for Ubuntu 12.04, for other builds replace the word "precise" with either "raring" (13.04), "quantal" (12.10) or "oneric" (11.10).

All packages are at https://launchpad.net/~nvbn-rm/+archive/ppa/+packages

**Comment by fleamour** [comment]
Latest Everpad AMD64 deb built by Alien (from 12.04 repos) fails to run under openSUSE 12.3 with following error:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 706, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 604, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: everpad==2.5dev

**Comment by ghost** [comment]
It looks to be something about the package requirements not being resolved. https://github.com/nvbn/everpad/wiki/how-to-install That page shows how to install from source but also lists the python library requirements.

**Comment by nvbn** [comment]
Look here http://docs.python.org/2/distutils/builtdist.html#creating-rpm-packages
If you want to publish package, use `master` branch.

If setup.py need changes for packaging, create pull request and i'll crate pacaking branch, like `package/ubuntu`

**Comment by Heart1010** [comment]
@fleamour Did you have success building a rpm package for openSUSE12.3 in the meanwhile?

**Comment by fleamour** [comment]
No, but NixNote (NeverNote) - An Open Source Evernote Clone works with just one manually installed dependency;

https://forums.opensuse.org/english/get-technical-help-here/applications/485269-running-nixnote-nevernote-problem.html

**Comment by Heart1010** [comment]
Ok, I also try to install everpad in openSUSE 12.3. I get this when I try to start it

$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 318, in main
    app.provider = get_provider(session_bus)
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 47, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files

So for two package requirements are not satisfied (tools and dbus). 

There is no "python-dbus" package in openSUSE, I installed dbus1-python for that (but something still missing!?)
And tools... "python-setuptools" also not there as package in openSUSE, installed python-distribute for that which provide setuptools files ("In this case add the package python-setuptools or preferably it's succcessor python-distribute to BuildRequires" found here https://en.opensuse.org/openSUSE:Packaging_Python#BuildRequires).

Any ideas what is mssing here?

**Comment by HLFH** [comment]
I support this request too :)

**Comment by mmitchell151** [comment]
I would also love to get this for opensuse

**Comment by stanislav-brabec** [comment]
I work on openSUSE package. It is now semi-working: https://github.com/nvbn/everpad/issues/335

**Comment by akuhl** [comment]
Not working for me (built from sources on openSUSE 12.3 with KDE 4.11). I satisfied all dependencies as packages from official repos but built python-pyside 1.2 from sources since this version was not yet available for opensuse.

As already said in issue #335 , Everpad is starting but fails to sync: "expected a character buffer object". It only retrieves 4 notes (out of < 200) and won't upload any created notes. NixNote 2-alpha works fine for me but is really inferior compared to the wonderful Everpad integration in KRunner.
