### ISSUE TITLE
Feature Request: Search

### ISSUE THREAD

**Issue by ghost** [nvbn/everpad#320]
Unless I'm missing it, is there search functionality? If not, can this please be added?

**Comment by cengiz-io** [comment]
I'm using Everpad on KDE and I can't search my notes. It seems that search functionality is dependent on Unity lens.

**Comment by zatrapilla** [comment]
+1

**Comment by e2jk** [comment]
Duplicate of #296.
Please close this issue to make it easier for the developers to focus by reducing noise.
