### ISSUE TITLE
everpad 2.5.6 on Ubuntu 13.04 : can't show authorize page if behind a proxy

### ISSUE THREAD

**Issue by magowiz** [nvbn/everpad#323]
Hi,
I just installed everpad and I would like to authorize it to sync with my existing account, 
the problem is that I'm behind a proxy and even if I specify the proxy with the format 
https_proxy="http://<username>:<password>@<proxy-ip>:<proxy-port>" I cannot authorize everpad, the authorize page stays blank forever and if launched from command line I get : 

  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 209, in change_auth
    'GET')

I'm using gnome shell and everpad package from ubuntu ppa.

**Comment by fjw** [comment]
same here for me. everpad dosn't seem to work behind a proxy? will this be fixed someday?
a internet-tool which dosn't work behind proxies is kind of useless...

**Comment by marknquinn** [comment]
I am experiencing the same issue even when the proxy is set  - other apps are working fine.

Everpad version: 2.5
API version: 6
Schema version: 5
