### ISSUE TITLE
Notes deleted on evernote website not synced

### ISSUE THREAD

**Issue by hotice** [nvbn/everpad#34]
Deleting notes on the Evernote website (including from the trash), doesn't delete them from the Everpad indicator / lens, even after trying to sync it 2-3 times.

Using Everpad 1.8.

**Comment by hotice** [comment]
This was fixed after a restart, closing

**Comment by nvbn** [comment]
What action you perform before tried to delete notes?

**Comment by hotice** [comment]
I've created about 2 notes using Everpad, then I've deleted some notes (4 or 5) from the Evernote website, then clicked the "sync" indicator menu item about 2-3 times and it said it synced, but the notes were still showing up in the indicator. That's about it as far as I can remember.

**Comment by hdave** [comment]
I have noticed that there is a limit to how frequently you can edit in Everpad, sync, and edit in Evernote, sync, etc. for testing purposes.  It seems to me that in comparing which note is newer, seconds do not count.  I could be wrong, but try and wait 1-2 full minutes between syncs when testing else you get strange results.
