### ISSUE TITLE
xfce search note

### ISSUE THREAD

**Issue by tlhc** [nvbn/everpad#343]
first :+1:  great job~~
when use xfce on ubuntu where shoud I search note ? would you add search bar in the main UI, thanks.. (ps: Gnome can search in panel bar..)

**Comment by DonnyBahama** [comment]
Same here. Really appreciate the app, but lack of search is painful. There must be some way to search on xfce...?

**Comment by e2jk** [comment]
Duplicate of #296.
Please close this issue to make it easier for the developers to focus by reducing noise.
