### ISSUE TITLE
Everpad on Ubuntu 13.10 works but inserts too much whitespace in posts 

### ISSUE THREAD

**Issue by torbengb** [nvbn/everpad#391]
When I edit an existing post using Everpad, and later view or edit that post in the Evernote web app, I notice that the number of newlines is doubled, and each newline is followed by a space. This also applies at the start of the post, and at the  start of each paragraph. 

I use a plain Ubuntu 13.10 with Unity and Firefox. 

I'm not on my machine right now so I can submit any requested debug info later. 

I'm not certain that Everpad is the culprit here, it might also be how Evernote receives and stores the edit, I guess. What steps  I take to narrow this down?

**Comment by torbengb** [comment]
Everpad was installed as per the instructions:

sudo add-apt-repository ppa:nvbn-rm/ppa
sudo apt-get update
sudo apt-get install everpad

**Comment by diogomatsubara** [comment]
This is likely a dupe of https://github.com/nvbn/everpad/issues/310 which has been fixed but hasn't been released. Vladimir, could you make a new release with the latest code, please?

**Comment by torbengb** [comment]
I agree, this is a dupe. Thank you for connecting it to the original!

**Comment by igor-borovkov** [comment]
Would really appreciate if somebody could make a new release with this fixed. Everpad is such a nice up, but stopped using it the next day because the issue is so annoying.

**Comment by ghost** [comment]
Everpad isn't usable for me at the moment, because it destroyed the formatting of all of my notes i opened with it, including some i worked on for hours.

I realy hope the fix gets published sone ;-)
