### ISSUE TITLE
Приложение не проходит авторизацию на сайте evernote

### ISSUE THREAD

**Issue by mdresvyankin** [nvbn/everpad#4]
Собстенно проблема. Версия приложения - текущий гит.
ОС - Fedora 17 Linux 3.5.0-2.fc17.x86_64 #1 SMP
При клике в трее на авторизироваться формирует ссылку вида https://www.evernote.com/OAuth.action?oauth_token=nvbn-цифры_буквы. После нажатия на дать доступ в браузере висит https://www.evernote.com/OAuth.action (пробовал konqueror, chrome, firefox). 

В настройках видно, что приложение авторизировано, но как его заставить работать дальше - становиться не понятным.

**Comment by nvbn** [comment]
Редирект на http://localhost:15216 не происходит?
После попытки авторизации процесс everpad-web-auth остаётся запущенным?

**Comment by mdresvyankin** [comment]
Редиректа нет. Процесс уходит в зомби.

**Comment by mdresvyankin** [comment]
Мало того, он сразу же уходит в зомби. Если это поможет

## ps aux | grep everpad

tree      1923  0.3  1.5 594124 63456 ?        S    22:17   0:00 /bin/python /bin/everpad
tree      1925  0.2  1.2 449564 48908 ?        S    22:17   0:00 /bin/python /usr/bin/everpad-provider
tree      1937  0.0  0.0      0     0 ?        Z    22:17   0:00 [everpad-web-aut] <defunct>
tree      2149  0.0  0.0 109400   872 pts/2    S+   22:20   0:00 grep --color=auto everpad

Все что пайтоновскаое стоит.

## rpm -qa | grep python

boost-python-1.48.0-13.fc17.x86_64
dbus-python-0.83.0-9.fc17.x86_64
gnome-python2-2.28.1-8.fc17.x86_64
libsemanage-python-2.1.6-3.fc17.x86_64
cryptsetup-python-1.5.0-1.fc17.x86_64
python-iwlib-1.2-1.fc17.x86_64
gnome-python2-desktop-2.32.0-9.fc17.x86_64
notify-python-0.1.1-20.fc17.x86_64
audit-libs-python-2.2.1-1.fc17.x86_64
python-pyside-1.1.0-1.fc17.x86_64
python-smbc-1.0.13-1.fc17.x86_64
python-zope-interface-3.7.0-1.fc17.x86_64
python-IPy-0.75-2.fc17.noarch
python-keyring-0.7-1.fc17.noarch
python-magic-5.11-2.fc17.x86_64
python-twisted-core-11.1.0-2.fc17.x86_64
newt-python-0.52.14-2.fc17.x86_64
python-chardet-2.0.1-4.fc17.noarch
python-lxml-2.3.3-1.fc17.x86_64
python-pycurl-7.19.0-10.fc17.x86_64
python-nss-0.12-3.fc17.x86_64
python-lockfile-0.9.1-2.fc17.noarch
plasma-scriptengine-python-4.8.4-1.fc17.x86_64
python-pwquality-1.1.1-1.fc17.x86_64
rpm-python-4.9.1.3-7.fc17.x86_64
python-pyblock-0.53-2.fc17.x86_64
setools-libs-python-3.3.7-24.fc17.x86_64
python-httplib2-0.7.4-6.fc17.noarch
python-tempita-0.5.1-1.fc17.noarch
python-slip-gtk-0.2.20-2.fc17.noarch
python-2.7.3-7.2.fc17.x86_64
gnome-python2-gnomekeyring-2.32.0-9.fc17.x86_64
python-ethtool-0.7-3.fc17.x86_64
python-decorator-3.3.3-1.fc17.noarch
python-paste-1.7.5.1-6.20111221hg1498.fc17.noarch
python-sqlalchemy-0.7.8-1.fc17.x86_64
python-simplejson-2.5.2-1.fc17.x86_64
policycoreutils-python-2.1.11-18.fc17.x86_64
python-urlgrabber-3.9.1-14.fc17.noarch
python-bugzilla-0.7.0-1.fc17.noarch
libselinux-python-2.1.10-3.fc17.x86_64
python-nose-1.1.2-2.fc17.noarch
python-deltarpm-3.6-0.7.20110223git.fc17.x86_64
gnome-python2-canvas-2.28.1-8.fc17.x86_64
libobasis3.6-extension-python-script-provider-3.6.0.4-104.x86_64
kross-python-4.8.4-1.fc17.x86_64
python-devel-2.7.3-7.2.fc17.x86_64
libxml2-python-2.7.8-7.fc17.x86_64
python-iniparse-0.4-4.fc17.noarch
python-cups-1.9.61-2.fc17.x86_64
abrt-addon-python-2.0.10-4.fc17.x86_64
python-oauth2-1.5.211-1.fc17.noarch
libreport-python-2.0.10-3.fc17.x86_64
python-imaging-1.1.7-6.fc17.x86_64
python-libs-2.7.3-7.2.fc17.x86_64
samba4-python-4.0.0-58alpha18.fc17.x86_64
python-kitchen-1.1.1-1.fc17.noarch
gamin-python-0.1.10-12.fc17.x86_64
python-meh-0.12-1.fc17.noarch
python-slip-dbus-0.2.20-2.fc17.noarch
libuser-python-0.57.6-1.fc17.x86_64
python-setuptools-0.6.27-2.fc17.noarch
python-slip-0.2.20-2.fc17.noarch
python-tdb-1.2.10-15.fc17.x86_64

Если есть возможность мключить отладку, подскажи как - сделаю.

**Comment by mdresvyankin** [comment]
yum install python-webpy.noarch - решил проблему. Спасибо.
