### ISSUE TITLE
How can I revert to previous version 2.5?

### ISSUE THREAD

**Issue by louisk100** [nvbn/everpad#404]
I also have problems with Everpad version 2.6.x on Ubuntu 12.04 LTS. 
How can I go back to stable previous version 2.5.?

**Comment by nvbn** [comment]
Hi i pushed reverted version to ppa.
Wait 2-3 hourse and you can update to it.

**Comment by louisk100** [comment]
Thank you. I will try later.
I loved version 2.5 and still use it on my notebook.
Louis K

Vladimir Iakovlev notifications@github.com schreef:

> Hi i pushed reverted version to ppa.
> Wait 2-3 hourse and you can update to it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nvbn/everpad/issues/404#issuecomment-36145179

## 

Verzonden van mijn telefoon met Kaiten Mail.

**Comment by louisk100** [comment]
This version of Everpad is okay. Issue can be closed. Thank you.

Op 26 feb. 2014 17:33 schreef "Vladimir Iakovlev" <notifications@github.com
