### ISSUE TITLE
No icon in task tray

### ISSUE THREAD

**Issue by ghstridr** [nvbn/everpad#406]
Running on Linux Mint 13 with Mate DE 1.2.0.

"sni-qt/16522" WARN  13:36:27.817 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Got bus address:  "unix:abstract=/tmp/dbus-AXI4S9ocsJ,guid=6631e5698b72e4887538e47700000054" 
Connected to accessibility bus at:  "unix:abstract=/tmp/dbus-AXI4S9ocsJ,guid=6631e5698b72e4887538e47700000054" 
Registered DEC:  true 
Registered event listener change listener:  true 
QSpiAccessible::accessibleEvent not handled:  "6"  obj:  QMenu(0x1b50ab0) "" 
QSpiAccessible::accessibleEvent not handled:  "7"  obj:  QMenu(0x1b50ab0) "" 
QSpiAccessible::accessibleEvent not handled:  "6"  obj:  QMenu(0x1b50ab0) "" 
QSpiAccessible::accessibleEvent not handled:  "7"  obj:  QMenu(0x1b50ab0) "" 
QSpiAccessible::accessibleEvent not handled:  "6"  obj:  QMenu(0x1b50ab0) "" 
QSpiAccessible::accessibleEvent not handled:  "7"  obj:  QMenu(0x1b50ab0) ""

**Comment by ghstridr** [comment]
![selection_001](https://f.cloud.github.com/assets/296345/2441443/a40c4990-ae14-11e3-88f7-0c780e3334be.png)

**Comment by ghstridr** [comment]
Additional note, in settings, selecting 'Black tray icon' in Appearance tab does make it appear.

**Comment by armc** [comment]
Any solution to this?

I have the exact same issue under Ubuntu Gnome 16.10

**Comment by ghstridr** [comment]
No longer using this project, so cleaning up and closing.
