### ISSUE TITLE
Everpad does not work on Ubuntu trusty

### ISSUE THREAD

**Issue by eitch** [nvbn/everpad#408]
Currently there is no PPA build for Everpad on Ubuntu 14.04 Trusty Tahr.

Is this planned? I can install the version for saucy, but this does not work and crashes immediately.

**Comment by luisdavim** [comment]
The version from saucy works on trusty.

**Comment by eitch** [comment]
It didn't start on my system. When I start it from the console, then the icon shows in the tray, but soon the everpad-provider crashes and i was not able to see any log or anything.

Where could i find log details about the provider?

**Comment by eitch** [comment]
I tried it again, and the everpad-provider simply segfaults after a few seconds
![everpad-provider_segfault](https://cloud.githubusercontent.com/assets/245382/2672581/457e7bdc-c0e8-11e3-8695-ad849ff6a929.png)

**Comment by nvbn** [comment]
I pushed version for trusty in ppa, is it works?

**Comment by eitch** [comment]
No, sadly this version segfaults as well.

**Comment by luisdavim** [comment]
I'm getting some segmentation faults as well but after a few tries it sarts working...

**Comment by eitch** [comment]
No, not even after a few tries. I started everpad and the tray icon menu is empty and when i click on it, in the console i get this:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 74, in update
    if self.app.provider.is_authenticated():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

**Comment by luisdavim** [comment]
My notes aren't syncing, this is the errors I get when running the provider in verbose mode:

(...)
/usr/lib/python2.7/dist-packages/sqlalchemy/sql/expression.py:1994: SAWarning: The IN-predicate on "resources.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  return o[0](self, self.expr, op, *%28other + o[1:]%29, **kwargs)
(...)
EDAMUserException(errorCode=10, parameter='Tag.name')
(...)
object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 458, in run
    self.perform()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 489, in perform
    if self._need_to_update():
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 74, in _need_to_update
    update_count = self.note_store.getSyncState(self.auth_token).updateCount
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2440, in getSyncState
    return self.recv_getSyncState()
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2456, in recv_getSyncState

**Comment by eitch** [comment]
Any status on this problem? I can't even give you more information because it just core dumps...

**Comment by MikeyG** [comment]
Do you know any python?  I have learned a little and I sort of think this might have been related to a problem I was having.

everpad is using this in class PullNote:

```
def _get_full_note(self, note_ttype):
    """Get full note"""
    return self.note_store.getNote(
        self.auth_token, note_ttype.guid,
        True, True, True, True,
    )
```

I think it use to return the actual resource binary, but no longer does return it.  The resource needs to be returned with a specific call to download it.

**Comment by eitch** [comment]
I don't see how that can be the problem as i can't even authenticate my account.

I did instyll pycharm and start the provider from there. This works, but when i start everpad it still can't receive a message on dbus:

/usr/bin/python2.7 /data/src/compile_temp/everpad/bin/everpad
Traceback (most recent call last):
  File "/data/src/compile_temp/everpad/everpad/pad/indicator.py", line 85, in update
    if self.app.provider.is_authenticated():
  File "/data/src/compile_temp/everpad/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

**Comment by MikeyG** [comment]
Oh sorry, I was talking about luisdavim problem.

**Comment by pvanheus** [comment]
Hi MikeyG - _get_full_note is called http://dev.evernote.com/doc/reference/NoteStore.html#Fn_NoteStore_getNote which seems to return the full content in the .content attribute. This is turn is process by models.Note.from_api (in everpad/provider/models.py) which reads the content and parses it using BeautifulSoup, basically selecting all the en-note elements and concatenating their content together. So I don't think that's the problem.

**Comment by MikeyG** [comment]
Okay, I think you are right.  I had two problems with the developer version of everpad.  First, it expects the resource binary to be returned from the getNote call which it does not.  Second, because of the evernote Rate Limits as of about November 2013, everpad will error if too many API calls are made in a certain period of time.

**Comment by SlavikZ** [comment]
**eitch** - take a look at my my pull request: https://github.com/nvbn/everpad/pull/415/files . It should fix your segfaults.
**luisdavim** - if you still have error **getSyncState** sync error - can you try my workaround: https://github.com/SlavikZ/unity-scope-everpad/issues/2#issuecomment-42746736 ?

**Comment by SlavikZ** [comment]
My workaround for **getSyncState** sync error was wrong. The real problem reason and its solution I describe here: https://github.com/nvbn/everpad/issues/355#issuecomment-43102353

**Comment by beeper22** [comment]
Starts on my 14.04, but shows no notes. Crashes on load, toolbar right click.....no menu.
Unusable at this point ....thought I had a real winning note app, coupled with evernote.

**Comment by MikeyG** [comment]
Is 14.04 based on Gnome?

**Comment by beeper22** [comment]
yes  the GTK toolkit is a popular tool and gedit is the default text editor

On Mon, May 19, 2014 at 9:46 AM, Mike Greene notifications@github.comwrote:

> Is 14.04 based on Gnome?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nvbn/everpad/issues/408#issuecomment-43505286
> .

## 

Reverend William Perdue

Universal Christ Christian Ministries

_"Be a realist, expect a miracle."_
-                          Sri Bhagwan*
