### ISSUE TITLE
Has anyone started (or completed) a gnome-shell for GNOME 3 implementation on this?

### ISSUE THREAD

**Issue by oliverseal** [nvbn/everpad#44]
Has anyone started (or completed) a gnome-shell for GNOME 3 implementation on this? I'm asking because I'd like to and googling hasn't really returned any results.
If no one has I'll dive it and give it a shot as a gnome extension. If they have, I'd love to get in there. Have you heard of anything like that?

**Comment by nvbn** [comment]
If you want to integrate gnome shell with everpad read https://github.com/nvbn/everpad/wiki/creating-DE-specific-extensions

**Comment by milanspk** [comment]
awesome. hopefully someone who understands a word of it will read that soon :)

**Comment by oliverseal** [comment]
Thanks, Vladimir. I started a new job so my own progress on this halted :/

**Comment by wishi** [comment]
We should coordinate on creating this fork.

**Comment by nvbn** [comment]
For basic gnome shell support please install https://extensions.gnome.org/extension/495/topicons/

**Comment by kmf** [comment]
I would be happy to donate for a feature like this. I'll donate $20 for it. Evernote is indispensable in my workflow.

**Comment by awamper** [comment]
I'm working on it. [Everpad Integration](https://github.com/awamper/everpad-integration)

**Comment by kmf** [comment]
Awesome... Will it be available on https://extensions.gnome.org?

**Comment by awamper** [comment]
yes

**Comment by awamper** [comment]
https://extensions.gnome.org/extension/677/everpad-integration/
