### ISSUE TITLE
Deleted notes doesn't behave properly

### ISSUE THREAD

**Issue by futape** [nvbn/everpad#446]
Notes deleted via the Evernote web app of another Evernote client still appear in Everpad.  
Notes deleted via Everpad aren't actually deleted.

**Comment by swobspace** [comment]
Have a look at your evernote profile -> applications. everpad has only right to create and update notes, but not to delete notes.

BTW: via evernote web deleted notes should be deleted in everpad, this may be a bug (not tested yet).
