### ISSUE TITLE
Authorize spelled incorrectly in Settings

### ISSUE THREAD

**Issue by SirSid** [nvbn/everpad#45]
Very minor issue, but I thought I'd bring it to your attention
Authorize is spelled as authorise in in settings

File as: Inconsequential

**Comment by oliverseal** [comment]
To be fair either "authorize" or "authorise" could be correct. Often times words that are spelled with the "z" in the suffix "ize" in US English are spelled "ise" in British documents.

**Comment by SirSid** [comment]
My mistake.
