### ISSUE TITLE
Everpad crash while saving note

### ISSUE THREAD

**Issue by AlexFalappa** [nvbn/everpad#46]
Everpad crashed while saving a newly edited note.

Here is the python traceback extracted from an apport crash log:

```
PythonArgs: ['/usr/bin/everpad']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 569, in save
     self.app.provider.update_note(self.note.struct)
   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
     **keywords)
   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
     message, timeout)
 DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Note not found
```

Environment:
- OS: Ubuntu 12.04 Precise Pangolin 64 bit
- DE: Unity
- Python: stock 2.7.3 provided with OS
- Everpad installed from PPA

**Comment by oliverseal** [comment]
Some notes on what I think might be at play here:
Looks like this failed during the 'load' phase. So either a the note wasn't actually added to the remote server in provider.create_note or there were connectivity problems there.

Just so it's clear, have you been having any connection issues, AlexFalappa? Can we rule internet connection problems out here? My wifi hardware seems to argue with Precise from time to time.

**Comment by AlexFalappa** [comment]
I could have had network problems while experiencing that crash, moreover I was behind a corporate firewall/proxy at that time.
Nevertheless I think the exception could be dealt with more gracefully and an error dialog shown to the user.

**Comment by jgomo3** [comment]
I even can't _"authorize"_ the app. I know i'm behind a proxy, so, how to tell **Everpad** the proxy configuration?

**Comment by nvbn** [comment]
Everpad not work behind proxy, because evernote sdk not work.

**Comment by jgomo3** [comment]
ever**NOTE** sdk not work? do you mean that the evernote sdk doesn't work behind proxys so **Evernote** itself won't work either?

Just in case, [an article about how to use Evernote with proxys](https://support.evernote.com/link/portal/16051/16058/Article/1635/Connecting-to-Evernote-through-a-Firewall-or-Proxy-Server).

**Comment by nvbn** [comment]
I mean this - https://github.com/evernote/evernote-sdk-python/issues/2

**Comment by fmoo** [comment]
evernote SDK has been hacked in everpad to now read the proxy configuration set in the environment by gnome networking config.

Feel free to reopen this if you're still having problems and provide details about your env to try to increase compatibility with this solution.

**Comment by jcruiz** [comment]
I'm behind a proxy, I've set up my proxy settings on Ubuntu 12.10 http/https all my applications work as expected. I just installed everpad and I'm not able to autorise. Does the authorization requires to be outside of a proxy?
