### ISSUE TITLE
Can't add attachment to note - v1.8.2 and 1.9

### ISSUE THREAD

**Issue by BlueCase** [nvbn/everpad#53]
Hi,
when I try to add a attachment to a note nothing happens.
Here the cli output during this action:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 413, in add
    self.add_attach(name)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 430, in add_attach
    hash=hashlib.md5(open(file_name).read()).hexdigest(),
IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: u'123

cheers,
BlueCase'

**Comment by nvbn** [comment]
What os and version you use?
Can you say full path of file, that you tried to attach?

**Comment by BlueCase** [comment]
Ubuntu 12.04 (System language: German)
Fullpath: /home/bluecase/Downloads/123

**Comment by BlueCase** [comment]
Thanks,
working...
