### ISSUE TITLE
Regression: Untouched "New" notes are saved and synced when closed

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#54]
This issue was gone for a while, but has re-emerged in Everpad 1.9.0 (actually, I think it reappeared earlier).

Steps to reproduce:

1) In the Everpad indicator select "Create Note"
2) When the new, empty, note appears, just close it (via the "x" button on the window manager) or the "X" on the toolbar.
3) Observe that there is no "Note saved..." notification pop-up
3) (optional) Repeat two more times
4) Sync
5) See the empty note(s) in Evernote and in Everpad Indicator drop down

I would have expected that an unmodified, new note, when closed, would not be saved to the local notes database and not sync'd to Evernote. After all, they have no content in them that is worth saving.

**Comment by ghost** [comment]
Confirmed here too in Everpad 1.9, Ubuntu 12.04, 64-bit.
