### ISSUE TITLE
Indicator drop-down list of notes is not sorted in order

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#55]
It is my understanding that the list of notes available in the Everpad indicator drop-down menu is the 20 more recently modified notes.  Is this correct?  If not, then which notes are selected to be in the list?

If so, then I would expect that the list of notes would be sorted in order of last modified date-time whereby the most recently modified note would be at the top of the drop-down menu.  However, this is not the case in at least two situations.

1) Newly created notes appear (typically) in the fourth place in the list.
2) Newly updated notes are not moved in the list, they stay in the same position.

I would expect that the list would be sorted both before a sync and after a sync.  That is, Everpad should use it's locally updated date-time to do the sorting.

**Comment by ghost** [comment]
Confirmed here too. It looks like it sorts by day, but then alphabetically by day. So I've created 4 notes today, and those notes ARE at the top of my indicator list, but in alphabetical order, not created-by order.

Generally, I can't find any way to see when a note was created or last modified. This is particularly frustrating in a search, where I have 50+ notes called "Friday Project Meeting" or similar.

**Comment by hdave** [comment]
This must have been fixed along the way as I can no longer reproduce it.
