### ISSUE TITLE
Everpad provider unable to sync

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#57]
Everpad-provider was not syncing anything...new notes or updates.   Running everpad-provider from the command line reports the following:

`EDAMUserException(errorCode=11, parameter='An invalid XML character (Unicode: 0x1b) was found in the element content of the document.')`

Deleting `~/.everpad` and restarting fixed the problem. 

I am sorry, but I cannot reproduce the issue, I just wanted you to be aware that some kind of regular note editing broke the provider...I don't know which ones though.

It would be great if everpad-provider would output the note title along with the error message.  If we then also had a way to get a hold of the note data to examine it would help us provide you better information when reporting bugs, etc.

**Comment by nvbn** [comment]
I work on debug output.

**Comment by hdave** [comment]
Thanks
