### ISSUE TITLE
Configurable Font Size? Use System Font Settings?

### ISSUE THREAD

**Issue by pointful** [nvbn/everpad#61]
I'm on a pretty high-rez screen and have my font-size set to "Larger" via the Universal Access settings in Unity. Everpad doesn't seem to be honoring that setting, and so the fonts are very small and hard to read.

**Comment by nvbn** [comment]
Everpad use system font settings, but maybe qtwebkit in editor use his settings.
Can you post screenshot of everpad editor with opened notebooks combobox?

**Comment by pointful** [comment]
Sure -- uploaded a series of screenshots to Skitch. Notice how the size all the fonts on the screen increases with the change in setting of the font size, but the content of the note in Everpad stays tiny.

First one with text size set to "Normal":
http://skitch.com/pointful/ei3r9/screenshot-from-2012-09-27-12-07-18
![Text Size Normal](http://img.skitch.com/20120927-n6xduxwrpgx1j7sqfs7pgpg3me.png)

Second one with text size set to "Large":
http://skitch.com/pointful/ei3fc/screenshot-from-2012-09-27-12-08-00
![Text Size Large](http://img.skitch.com/20120927-ds21j8p5aue3baugsneieneea.png)

Third one with text size set to "Larger":
http://skitch.com/pointful/ei3fa/screenshot-from-2012-09-27-12-08-20
![Text Size Larger](http://img.skitch.com/20120927-cafh521sqxbfghcp1ub678e2yr.png)
