### ISSUE TITLE
Wishlist: Lens search by tag

### ISSUE THREAD

**Issue by bpteague** [nvbn/everpad#63]
New Evernote / Everpad user - neat project.

Could the Unity lens search by tag, as well as title and content?  At the moment, it doesn't seem to.

**Comment by hdave** [comment]
That is cool idea.  Could we also include the name of the notebook?

FYI  - I think issues #35 and #57 can be closed, yes?

**Comment by nvbn** [comment]
Currently you can search by tags with filters. But ok, in next release it will be.

**Comment by bpteague** [comment]
Ah - I hadn't seen the filters.  (I'm not a Unity power user, can you tell?)  

On the other hand, my tags and notebooks don't seem to be showing up under the filters anyways.  I'll poke at it and file a new bug.

**Comment by hdave** [comment]
How did I miss that before?  That's awesome!  Places, Notebook, and Tags are in there as filters.  I guess I've always searched directly from the home page...
