### ISSUE TITLE
Case-sensitive search

### ISSUE THREAD

**Issue by paulelms** [nvbn/everpad#64]
I think the search should not be case sensitive, at least when I type in a search query in lowercase

**Comment by hdave** [comment]
On my system I am not seeing this behavior.  Searches in the Unity lens are case insensitive for me.

`Architecture: amd64
Version: 1.9.1-0~precise`

**Comment by paulelms** [comment]
Affects only search in Russian ;-)

ÞÅÔ×ÅÒÇ, 27 ÓÅÎÔÑÂÒÑ 2012 Ç. ÐÏÌØÚÏ×ÁÔÅÌØ hdave ÐÉÓÁÌ:

> On my system I am not seeing this behavior. Searches in the Unity lens are
> case insensitive for me.
> 
> Architecture: amd64
> Version: 1.9.1-0~precise
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/nvbn/everpad/issues/64#issuecomment-8936270.

## 

Sent from Gmail Mobile

**Comment by nvbn** [comment]
Бага в алхимии, но не страшно, поиск скоро будет на xapian.

28.09.2012 20:50, Paul Elms пишет:

**Comment by paulelms** [comment]
Спасибо. А когда фикс попадет в версию из ppa? =) Сначала думал что бага не пофикшена, но посмотрел на коммит и в /usr/share/pyshared/everpad/provider/service.py - там фикса пока нет.
