### ISSUE TITLE
Add dependency to ppa artifact: python-oauth2

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#7]
I was unable to log in to Evernote without have this additional module installed.  I believe that  python-oauth2 should be a required dependency of this app.

**Comment by nvbn** [comment]
Latest version (1.0.5-3) in ppa has python-oauth2 dependency:

Version: 1.0.5-3~precise
Depends: python-pyside.qtcore, python-pyside.qtgui, python-dbus, python-beautifulsoup, sni-qt, python-pysqlite2, python-keyring, python-webpy, python-support, python-sqlalchemy, python-oauth2, python-unity-singlet
