### ISSUE TITLE
Everpad 1.10.0 not syncing

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#73]
Running ppa version1.10.0 on Ubuntu 12.04 64 bit.

everpad-provider does not seem to be syncing.  Running everpad-provider in terminal yields no output whatsoever.   If I delete ~/.everpad, then restart, it downloads all my notes during the first sync.  However, there is never any subsequent sync (that I can detect) and no error messages coming from either evernote-provider or evernote in the terminal.

Have no idea what is causing this, but it is very repeatable.

**Comment by nvbn** [comment]
Try run `everpad-provider --verbose` for debug output

**Comment by hdave** [comment]
Thanks -- the error message is:

`EDAMUserException(errorCode=11, parameter='An invalid XML character (Unicode: 0x1b) was found in the element content of the document.')`

This is the second time I've gotten this error message on a 2-3 page note I've created entirely from within Everpad.  I then deleted the offending note and got another error message on a very short two sentence note:

`EDAMUserException(errorCode=11, parameter='Element type "title" must be declared.')`

I then delete that offending note and got another error message:

`EDAMUserException(errorCode=11, parameter='Attribute "name" must be declared for element type "span".')`

Deleted this and then sync worked...Hope this helps.

**Comment by nvbn** [comment]
You used evernote email api for creating notes?

**Comment by hdave** [comment]
Used the Everpad user interface (indicator) to create these notes.   But now that I think about it, my laptop _may_ have been offline when I created them...but I don't think so.

**Comment by hdave** [comment]
Did some more testing.  I can fairly reliably recreate this problem:

1) Take machine offline
2) Create a new note, edit it
3) Save and close the new note
4) repeatedly edit and save it
5) reboot machine into online state
6) synchronize notes
7) observe the failure:

`EDAMUserException(errorCode=11, parameter='An invalid XML character (Unicode: 0x1b) was found in the element content of the document.')`

**Comment by hdave** [comment]
This issue and #69 seem like they might be the same thing.  It's as if the note is getting corrupted somehow.

**Comment by hdave** [comment]
I just got this issue again (errorcode=11) on another note when I was online the entire time, so I was wrong -- it really has nothing to do with being online or offline.  Running 1.11.1-0~precise.

**Comment by zhengbli** [comment]
The same problem on my computer. Thinkpad T430,  ubuntu 12.10 64 bit. Everpad 1.10
Errorcode = 11 and cannot sync

**Comment by fmoo** [comment]
@hdave , @tinza123 - can you confirm this is still happening with the latest changes?

**Comment by hdave** [comment]
I cannot reproduce this as of 2.0.0, so I will go ahead and close it.
