### ISSUE TITLE
gnome-shell

### ISSUE THREAD

**Issue by gfavaro** [nvbn/everpad#75]
Any plans to make it compatible with gnome3, or add an interface to search/manage notes?

**Comment by nvbn** [comment]
Latest version have note management window, click to "all notes" in indicator.
I don't have plans to create integration with gnome shell, but everyone can create it using everpad-provider api. And i will merge it into repository.

**Comment by acutbal** [comment]
Great!! I hadn't seen it... Growing the quality of Everpad!!

**Comment by fmoo** [comment]
gnome3 support dupe of #44.

Everything else is pretty much done.

**Comment by flenzi** [comment]
It doens't work for me in ubuntu with gnome3:
"sni-qt/9059" WARN  15:52:12.297 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE"

**Comment by fmoo** [comment]
Yeah I couldn't get it working on gnome in Ubuntu either...

**Comment by nvbn** [comment]
It's sni-qt bug, please create bug report for it - https://bugs.launchpad.net/sni-qt/+bugs

**Comment by nvbn** [comment]
Or remove sni-qt.

**Comment by jmergy** [comment]
Bummer. Unable to use Everpad. I ripped-out all things Unity and running Gnome. I am currently just running Evernote Windows under WINE >> http://mergy.org/2012/11/get-the-evernote-windows-application-on-ubuntu-12-10-via-wine/

**Comment by nvbn** [comment]
For basic gnome shell support please install https://extensions.gnome.org/extension/495/topicons/

**Comment by lesliev** [comment]
On gnome-shell 3.6.2-0ubuntu0.2, using the above extension worked for me. Trying to select "Black tray icon" seemed to do nothing so I did this: sudo cp /usr/share/icons/hicolor/64x64/apps/everpad-mono.png /usr/share/icons/hicolor/128x128/apps/everpad.png
Now the tray icon looks ok on a default black Gnome3 top bar.

**Comment by kendoori** [comment]
@lesliev Thanks for this... your trick worked for me
