### ISSUE TITLE
Feedback after authorization

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#8]
Once Everpad has been authorized to access Evernote via the application indicator, there is no feedback.  At minimum, it would be nice to see:

1) notification that everpad has begun to synhronize with Evernote and it could take several minutes
2) some kind of status on the pull-down menu that says "Sync in progress...."
3) initial sync has completed notification

For me the initial sync takes about 50 seconds.

**Comment by hdave** [comment]
Part 2 of this issue is completed as of v1.5.0

I guess at this point, it would just be nice to see some kind of warning/message after (or during) the initial authorization that the initial sync could take a minute or two depending on your number of notes and size of attachments.  Either way IMO - this issue can be closed.

**Comment by nvbn** [comment]
Wait when ubuntu or evernote fix ssl issue. After that authentication can be in embed webkit and app will trace the authorization and first synchronization .

**Comment by hdave** [comment]
Has the SSL issue been addressed?  I think the only thing we really need to close this issue are the beginning and ending notifications around the intial sync.

**Comment by nvbn** [comment]
Ssl issue mokeypatched. And now first sync displayed in indicator especially.
