### ISSUE TITLE
Remove Resource does not appear until note is reopened without inlined image

### ISSUE THREAD

**Issue by fmoo** [nvbn/everpad#80]
Whether or not "Remove Resource" appears on an attached image is a little buggy.

If I inline and then remove the resource from the message body (until I reopen the note again), "Remove Resource" disappears from the context menu.

If I save and reopen the note, it will reappear.

**Comment by fmoo** [comment]
So I have a fix for this almost ready, but it's kind of ugly as it has to work around something interesting going on with contenteditable=True in webkit.

It looks like, if you go to the newline prior to the embedded image, and press [delete], instead of reparenting the <img> tag, WebKit deletes and re-creates the <img> tag outside of the <div> that it had been using to create the newline.

The end result is that any event listeners that had been installed (for example, the console.log() one that emits the "context") just stop working, despite the image still being present.

**Comment by nvbn** [comment]
My fixes is simplest =)
