### ISSUE TITLE
Wishlist : All Notes - add date column

### ISSUE THREAD

**Issue by ghost** [nvbn/everpad#87]
When using "All Notes", I find that without a date column, I can't usefully select the required note. I have many repeat meetings and being able to see which note is which, by date, would be superb.

Screenshot of my issue is here : http://imgur.com/FglF9

**Comment by fmoo** [comment]
@nvbn - can we close this out?  Or did you want to cut a new release first?

**Comment by nvbn** [comment]
Yes, bug tracker used for git version, not ppa =)
