### ISSUE TITLE
No close button for dialogs

### ISSUE THREAD

**Issue by utkarshsins** [nvbn/everpad#88]
There is no close button 'X' for 'Settings and Management' dialog and 'All Notes' dialog. The user has to right click the title bar and choose close from the context window to close both the windows.

<pre>
System:
    Gnome 3.4
    Debian Wheezy
</pre>

**Comment by nvbn** [comment]
Can you post screenshot?

**Comment by utkarshsins** [comment]
Will these work?

<pre>
Settings and Management dialog : no close button in upper right corner
</pre>

http://img.im/i/view-4061-hgba47

<pre>
Context Menu to close the dialog
</pre>

http://img.im/i/view-4060-lty3k6

**Comment by fmoo** [comment]
I _think_ this is because Settings and Management Dialog subclasses QDialog instead of QMainWindow

@utkarshsins - What window manager / decorator are you using?  Vanilla gnome?

**Comment by utkarshsins** [comment]
@fmoo Yes, that is the issue. I am running Vanilla Gnome, 3.4.

Adding Window Flags for the Close Button, fixes the issue for me.

$ git diff

<pre>
diff --git a/everpad/interface/list.py b/everpad/interface/list.py
index e429110..15118ea 100644
--- a/everpad/interface/list.py
+++ b/everpad/interface/list.py
@@ -14,6 +14,7 @@ class Ui_List(object):
         List.setObjectName("List")
         List.resize(800, 600)
         List.setModal(False)
+        List.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
         self.verticalLayout = QtGui.QVBoxLayout(List)
         self.verticalLayout.setObjectName("verticalLayout")
         self.splitter = QtGui.QSplitter(List)
diff --git a/everpad/interface/management.py b/everpad/interface/management.py
index bb78451..228d4c3 100644
--- a/everpad/interface/management.py
+++ b/everpad/interface/management.py
@@ -14,6 +14,7 @@ class Ui_Dialog(object):
         Dialog.setObjectName("Dialog")
         Dialog.resize(396, 372)
         Dialog.setModal(False)
+        Dialog.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
         self.verticalLayout = QtGui.QVBoxLayout(Dialog)
         self.verticalLayout.setObjectName("verticalLayout")
         self.tabWidget = QtGui.QTabWidget(Dialog)
</pre>

**Comment by fmoo** [comment]
Okay, so apparently, qt-designer doesn't support configuration of the windowFlags property.  I hacked the xml file to include 

```
  <property name="windowFlags">
   <enum>Qt::WindowCloseButtonHint</enum>
  </property>
```

And while pyside-uic generates the correct code in the .py file, when I go to re-open the .ui files in designer, it strips out the property.

The cleanest solution I can think of is a "promoted" QDialog that overrides the constructor to always do flags f |= QtCore.Qt.WindowCloseButtonHint.

**Comment by fmoo** [comment]
So I'd really like to repro this on my machine before committing to that fix.

Are you using the emerald window decorator?   If so, do you have the emerald-theme-manager installed?  If so, can you run that, go to Themes Settings > Edit Themes and copy paste the value of "Titlebar" here?  also maybe click Export..., save the .emerald file, and upload that somewhere I can grab it?

I'm still leaning towards using QMainWindow instead of QDialog for these windows, since they're pretty much windows, not dialogs.

**Comment by utkarshsins** [comment]
I am not running Compiz, or Ubuntu for that matter. From what I could find online right now, Emerald is a Window Decorator used with Compiz Window Manager only. 

So, I am probably not using Emerald Window Decorator. I am using Gnome Shell 3.4, on a Debian Wheezy system, that uses Mutter Window Manager. I can't seem to figure out how Window Decorators work with Gnome Shell.  Neither is emerald-theme-manager available in Debian repositories.

What should I do to help you out?

**Comment by nvbn** [comment]
"Settings and management" is a dialog and it's a standard behavior for gnome shell.
And look to http://stackoverflow.com/questions/8691025/qt-qdialog-and-gnome-3-how-to-display-the-close-button-title-bar-and-make-it-mo
