### ISSUE TITLE
Enhancement: Find functionality within note

### ISSUE THREAD

**Issue by neilhuang** [nvbn/everpad#90]
Currently once a note is opened (possibly through the unity lens), the opened note cannot be further narrowed down with phrases. 

There are two use cases to approach this:
1. Use unity lens to find a note with user's desired string. Once the note is opened, the user's desired string from unity is then automatically highlighted in the opened note.
1. Each spawned note window would need to have its own find process.
2. Maybe combine both? =)

**Comment by fmoo** [comment]
All that's left is to make the unity search auto-fill the in-note search.

**Comment by fmoo** [comment]
Okay @neilhuang - all done!

**Comment by neilhuang** [comment]
Feature verified working. Looks great. Thanks a lot!
