### ISSUE TITLE
Wishlist - Remember sorting in "All Notes" window

### ISSUE THREAD

**Issue by ghost** [nvbn/everpad#98]
Now that a date column has been added (issue #87), I can sort my notebooks by date. However, by default, there is no sort option specified.

When I sort by a given column, it would be useful for Everpad to remember that I'm sorting by that column, especially between sessions.

In fact, clicking on any notebook on the left-pane (even the currently chosen notebook!) resets the sort option to "Title, a-z", whereas I always use "Created, z-a" in order to show most recent notes first.

I notice that NixNote also fails to honour persistent sorting, so perhaps this is a linux issue!

**Comment by fmoo** [comment]
> NixNote also fails to honour persistent sorting, so perhaps this is a linux issue

Nope, just lazy programmers!

**Comment by fmoo** [comment]
@scaine - I have another diff ready that persists this setting across restarts, but that may be overkill.

lmk what you think and feel free to close this out if the current solution is adequate.

**Comment by ghost** [comment]
I'd personally love for this to persist across restarts, Peter, but very happy that it persists across sessions just now. I'll leave it up to you.
Neil.

**Comment by fmoo** [comment]
@nvbn - cool, this is in.  Can we close this task out?

**Comment by fmoo** [comment]
fixed in trunk
